"""Atualizando banco

Revision ID: 08c73f42399e
Revises: b58b9fe33b5a
Create Date: 2025-02-14 11:05:48.064296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08c73f42399e'
down_revision: Union[str, None] = 'b58b9fe33b5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('idioma', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'idioma')
    # ### end Alembic commands ###
