"""Mensagem da para

Revision ID: 1a2dfac501e8
Revises: 8b3db6d60696
Create Date: 2025-01-10 11:11:46.429924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a2dfac501e8'
down_revision: Union[str, None] = '8b3db6d60696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anuncio', sa.Column('ativo', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anuncio', 'ativo')
    # ### end Alembic commands ###
