"""Revisão final

Revision ID: 354d0ca5ce30
Revises: e04e0a4b5f87
Create Date: 2025-01-22 14:27:26.365923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '354d0ca5ce30'
down_revision: Union[str, None] = 'e04e0a4b5f87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_anuncio_id'), 'anuncio', ['id'], unique=False)
    op.create_foreign_key(None, 'endereco_envio', 'pedido', ['pedidoID'], ['id'])
    op.add_column('pedido', sa.Column('data_confirmacao_recebimento', sa.DateTime(), nullable=True))
    op.add_column('pedido', sa.Column('data_limite_confirmacao', sa.DateTime(), nullable=True))
    op.alter_column('pedido', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pedido', 'produto_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_pedido_id'), 'pedido', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedido_id'), table_name='pedido')
    op.alter_column('pedido', 'produto_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pedido', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('pedido', 'data_limite_confirmacao')
    op.drop_column('pedido', 'data_confirmacao_recebimento')
    op.drop_constraint(None, 'endereco_envio', type_='foreignkey')
    op.drop_index(op.f('ix_anuncio_id'), table_name='anuncio')
    # ### end Alembic commands ###
