"""Revisão final

Revision ID: 49cbe94ec1a0
Revises: 354d0ca5ce30
Create Date: 2025-01-28 12:31:20.262510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49cbe94ec1a0'
down_revision: Union[str, None] = '354d0ca5ce30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'endereco_envio', 'pedido', ['pedidoID'], ['id'])
    op.alter_column('pedido', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pedido', 'produto_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_pedido_id'), 'pedido', ['id'], unique=False)
    op.drop_constraint('pedido_produto_id_fkey', 'pedido', type_='foreignkey')
    op.drop_constraint('pedido_customer_id_fkey', 'pedido', type_='foreignkey')
    op.create_foreign_key(None, 'pedido', 'usuarios', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'pedido', 'produto', ['produto_id'], ['id'])
    op.add_column('produto', sa.Column('renovacao_automatica', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produto', 'renovacao_automatica')
    op.drop_constraint(None, 'pedido', type_='foreignkey')
    op.drop_constraint(None, 'pedido', type_='foreignkey')
    op.create_foreign_key('pedido_customer_id_fkey', 'pedido', 'usuarios', ['customer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('pedido_produto_id_fkey', 'pedido', 'produto', ['produto_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_pedido_id'), table_name='pedido')
    op.alter_column('pedido', 'produto_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pedido', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'endereco_envio', type_='foreignkey')
    # ### end Alembic commands ###
