"""Mensagem da migração

Revision ID: 4ea518f74993
Revises: 
Create Date: 2025-01-06 13:11:50.102265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ea518f74993'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('status_visivel_comprador', sa.String(length=20), nullable=True))
    op.add_column('produto', sa.Column('status_visivel_vendedor', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produto', 'status_visivel_vendedor')
    op.drop_column('produto', 'status_visivel_comprador')
    # ### end Alembic commands ###
