"""Atualizando banco

Revision ID: b58b9fe33b5a
Revises: cec0f50ab47c
Create Date: 2025-02-12 14:53:38.177752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b58b9fe33b5a'
down_revision: Union[str, None] = 'cec0f50ab47c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anuncios_usuarios', sa.Column('cliques', sa.Integer(), nullable=True))
    op.add_column('usuarios', sa.Column('bloqueado', sa.Boolean(), nullable=True))
    op.add_column('usuarios', sa.Column('sexo', sa.String(length=20), nullable=True))
    op.add_column('usuarios', sa.Column('nome_pagina', sa.String(length=100), nullable=True))
    op.add_column('usuarios', sa.Column('biografia', sa.String(length=500), nullable=True))
    op.create_unique_constraint(None, 'usuarios', ['contacto'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_column('usuarios', 'biografia')
    op.drop_column('usuarios', 'nome_pagina')
    op.drop_column('usuarios', 'sexo')
    op.drop_column('usuarios', 'bloqueado')
    op.drop_column('anuncios_usuarios', 'cliques')
    # ### end Alembic commands ###
