"""Atualizando banco

Revision ID: e73f359d4e84
Revises: 08c73f42399e
Create Date: 2025-02-17 11:35:27.146485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e73f359d4e84'
down_revision: Union[str, None] = '08c73f42399e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('role', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'role')
    # ### end Alembic commands ###
